### PR TITLE
More accurate wave functions and libxc interface

### LINKED ISSUE #1: More accurate expansions instead of Clementi-Roetti data
Hi,

this is no doubt an useful piece of code. However, the Clementi-Roetti wave functions are quite bad for heavier atoms; better-quality data has been reported by e.g. Koga et al in [J. Chem. Phys. 103, 3000 (1995)](https://doi.org/10.1063/1.470488), which is within 13 uEh from the numerical limit for all atoms.

### PR DESCRIPTION
**Pull request by susilehtola**
As the title suggests, this pull request switches the library to the use of more accurate wave functions than the Clementi-Roetti tabulations which have errors up to tens of milliHartree(!).

Data is now included for all atoms, and is parsed automatically from output files of the ATOM program, which I received on demand from Ajit Thakkar. Unfortunately, the output is in fixed precision, which means that the coefficients are not very accurate. I've asked Ajit to supply floating-point values, but these can be merged in later.

The pull also includes a libxc interface, which can be used to evaluate xc functionals. The code will now print PBE exchange energies by default if it's run as the main program.

Fixes #1

### CODE REVIEW

**Comment by JFurness1** [comment]
Thanks Susi! This looks great. I had seen your earlier comment but not found the time to address upgrading the data yet.

I'll take a look so I understand the changes, then I'll merge them into the main branch.

This is a great addition, and I'll be happy to not be pulling the coefficients out by hand now!

**Comment by JFurness1** [comment]
Just had a chance to look over your code. Looks great Susi! 

Whenever you think it's ready I'll merge this in with my original branch.

**Comment by susilehtola** [comment]
OK, I think it is good enough. I'll let you do the honors.

**Comment by JFurness1** [comment]
Much obliged. Thanks again for the contributions!

**Pull request merged**
